import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ChevronRight, Save, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

type FormState = { name: string; description: string; avatarSymbol: string; behavioralInstruction: string; storyPremise: string; roles: string; worldRules: string; endingConditions: string; visibility: "public" | "private"; allowTelegramMedia: boolean };
const blank: FormState = { name: "", description: "", avatarSymbol: "✦", behavioralInstruction: "", storyPremise: "", roles: "", worldRules: "", endingConditions: "", visibility: "private", allowTelegramMedia: false };

function Step({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return <section className="story-panel p-6 sm:p-7"><span className="archive-number">{number}</span><h2 className="mt-3 text-xl font-semibold">{title}</h2>{children}</section>;
}

export default function CharacterEditorPage() {
  const [, params] = useRoute("/characters/:id/edit"); const [, startParams] = useRoute("/characters/:id/start");
  const storyBotId = Number(params?.id ?? startParams?.id ?? 0); const editing = Boolean(params?.id); const [, setLocation] = useLocation(); const utils = trpc.useUtils();
  const detail = trpc.storyBots.get.useQuery({ storyBotId }, { enabled: storyBotId > 0 });
  const [form, setForm] = useState<FormState>(blank); const [chosenRole, setChosenRole] = useState("");
  const create = trpc.storyBots.create.useMutation({ onSuccess: bot => { utils.storyBots.listAccessible.invalidate(); toast.success("پروندهٔ جهان ثبت شد."); setLocation(`/characters/${bot?.id}/edit`); } });
  const update = trpc.storyBots.update.useMutation({ onSuccess: () => { utils.storyBots.listAccessible.invalidate(); toast.success("تغییرات پرونده ذخیره شد."); } });
  const createRun = trpc.storyRuns.create.useMutation({ onSuccess: run => { if (run?.run) setLocation(`/chat/${run.run.id}`); else toast.error("شروع داستان ممکن نشد."); } });
  useEffect(() => { if (detail.data) { const bot = detail.data; setForm({ name: bot.name, description: bot.description, avatarSymbol: bot.avatarSymbol, behavioralInstruction: bot.behavioralInstruction, storyPremise: bot.storyPremise, roles: bot.roleOptions.join("، "), worldRules: bot.worldRules, endingConditions: bot.endingConditions, visibility: bot.visibility, allowTelegramMedia: bot.allowTelegramMedia }); setChosenRole(bot.roleOptions[0] ?? ""); } }, [detail.data]);
  const patch = (key: keyof FormState, value: string | boolean) => setForm(current => ({ ...current, [key]: value }));
  const payload = () => ({ name: form.name, description: form.description, avatarSymbol: form.avatarSymbol || "✦", behavioralInstruction: form.behavioralInstruction, storyPremise: form.storyPremise, roleOptions: form.roles.split(/[،,\n]/).map(item => item.trim()).filter(Boolean), worldRules: form.worldRules, endingConditions: form.endingConditions, visibility: form.visibility, allowTelegramMedia: form.allowTelegramMedia });
  const save = () => { const data = payload(); if (editing) update.mutate({ storyBotId, changes: data }); else create.mutate(data); };

  if (startParams?.id && detail.data) return <div className="archive-page p-5 sm:p-10"><div className="mx-auto max-w-2xl"><button onClick={() => setLocation("/discover")} className="flex items-center gap-1 text-sm text-muted-foreground"><ChevronRight className="size-4" />بازگشت به کشف</button><section className="mt-8 border-y archive-rule py-12 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-secondary text-2xl text-secondary-foreground">{detail.data.avatarSymbol}</span><p className="archive-kicker mt-6">نقطهٔ شروع تو</p><h1 className="mt-2 text-3xl font-semibold">{detail.data.name}</h1><p className="mt-3 text-muted-foreground">{detail.data.description}</p><div className="mt-8 text-right"><Label>نقش خودت را انتخاب کن</Label><select value={chosenRole} onChange={event => setChosenRole(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-border bg-card px-3 text-sm"><option value="">یک نقش انتخاب کنید</option>{detail.data.roleOptions.map(role => <option key={role} value={role}>{role}</option>)}</select></div><Button disabled={!chosenRole || createRun.isPending} onClick={() => createRun.mutate({ storyBotId, selectedRole: chosenRole })} className="mt-6 w-full rounded-full">{createRun.isPending ? "در حال گشودن جهان…" : "شروع داستان"}<Sparkles className="mr-2 size-4" /></Button></section></div></div>;
  if (editing && detail.isLoading) return <div className="archive-page p-10 text-muted-foreground">در حال گشودن پروندهٔ جهان…</div>;

  return <div className="archive-page"><div className="container max-w-5xl py-10 sm:py-14"><header className="flex items-end justify-between gap-4 border-b archive-rule pb-8"><div><p className="archive-kicker">CREATOR STUDIO / پروندهٔ جهان</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{editing ? "ویرایش پروندهٔ جهان" : "ثبت یک جهان تازه"}</h1><p className="mt-3 leading-8 text-muted-foreground">اطلاعات این پرونده، نحوهٔ رفتار شخصیت، مرز جهان و شکل پایان داستان را تعیین می‌کند.</p></div><Button variant="outline" onClick={() => setLocation("/characters")} className="rounded-full border-border bg-transparent">انصراف</Button></header>
    <form onSubmit={event => { event.preventDefault(); save(); }} className="mt-9 space-y-6"><Step number="01 / هویت" title="شناسنامهٔ شخصیت"><div className="mt-6 grid gap-4 sm:grid-cols-[.22fr_1fr]"><div><Label>نماد</Label><Input value={form.avatarSymbol} maxLength={12} onChange={e => patch("avatarSymbol", e.target.value)} className="mt-2 rounded-xl text-center text-xl" /></div><div><Label>نام شخصیت</Label><Input value={form.name} onChange={e => patch("name", e.target.value)} placeholder="مثلاً: آستر، راهنمای ستاره‌ها" className="mt-2 rounded-xl" /></div></div><div className="mt-5"><Label>توضیح کوتاه</Label><Textarea value={form.description} onChange={e => patch("description", e.target.value)} className="mt-2 min-h-24 rounded-xl" placeholder="کاربر پیش از شروع داستان چه چیزی باید بداند؟" /></div><div className="mt-5"><Label>دستور رفتاری شخصیت</Label><Textarea value={form.behavioralInstruction} onChange={e => patch("behavioralInstruction", e.target.value)} className="mt-2 min-h-36 rounded-xl" placeholder="لحن، دانش، خط قرمزها و شیوهٔ رفتار شخصیت را بنویس…" /></div></Step>
      <Step number="02 / جهان" title="نقشه و پایان روایت"><div className="mt-6"><Label>پیش‌زمینهٔ داستان</Label><Textarea value={form.storyPremise} onChange={e => patch("storyPremise", e.target.value)} className="mt-2 min-h-32 rounded-xl" placeholder="داستان از کجا آغاز می‌شود؟ چه چیزی در خطر است؟" /></div><div className="mt-5"><Label>نقش‌های قابل انتخاب</Label><Input value={form.roles} onChange={e => patch("roles", e.target.value)} className="mt-2 rounded-xl" placeholder="مثلاً: هری پاتر، هرمیون، دانش‌آموز جدید" /><p className="mt-2 text-xs text-muted-foreground">نقش‌ها را با ویرگول یا «،» جدا کنید.</p></div><div className="mt-5"><Label>قواعد جهان</Label><Textarea value={form.worldRules} onChange={e => patch("worldRules", e.target.value)} className="mt-2 min-h-28 rounded-xl" placeholder="چه چیزهایی ممکن یا ناممکن‌اند؟" /></div><div className="mt-5"><Label>شرایط پایان داستان</Label><Textarea value={form.endingConditions} onChange={e => patch("endingConditions", e.target.value)} className="mt-2 min-h-28 rounded-xl" placeholder="چه رخدادی پایان معتبر این داستان را مشخص می‌کند؟" /></div></Step>
      <Step number="03 / دسترسی" title="انتشار و تلگرام"><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="rounded-xl border border-border bg-secondary/50 p-4"><span className="text-sm font-medium">نمایش جهان</span><select value={form.visibility} onChange={e => patch("visibility", e.target.value as "public" | "private")} className="mt-3 h-10 w-full rounded-lg border border-border bg-card px-3 text-sm"><option value="private">خصوصی — فقط برای شما و کاربران مجاز</option><option value="public">عمومی — قابل کشف برای همه</option></select></label><label className="flex items-center justify-between gap-4 rounded-xl border border-border bg-secondary/50 p-4"><span><span className="block text-sm font-medium">رسانهٔ تلگرام</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">برای شخصیت‌های معاصر که استفاده از تلفن برایشان منطقی است.</span></span><Switch checked={form.allowTelegramMedia} onCheckedChange={value => patch("allowTelegramMedia", value)} /></label></div></Step>
      <div className="flex justify-end"><Button disabled={create.isPending || update.isPending} type="submit" className="rounded-full">{create.isPending || update.isPending ? "در حال ثبت…" : "ثبت پروندهٔ جهان"}<Save className="mr-2 size-4" /></Button></div>
    </form></div></div>;
}
