import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowUpLeft, BookOpen, Compass, MessageCircleMore, Plus, Send, Sparkles } from "lucide-react";
import { useLocation } from "wouter";

export default function Overview() {
  const [, setLocation] = useLocation();
  const { data: runs, isLoading } = trpc.storyRuns.list.useQuery();
  const activeRuns = runs?.filter(item => item.run.status === "active") ?? [];
  const featuredRun = activeRuns[0];

  return <div className="archive-page"><div className="container py-10 sm:py-14">
    <header className="grid gap-8 border-b archive-rule pb-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-3"><p className="archive-kicker">GIPO / پروندهٔ شخصی</p><span className="archive-number">CAT. 01</span></div><h1 className="mt-3 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">روایت‌هایی که
      <span className="text-primary"> ادامه داده‌ای.</span></h1><p className="mt-4 max-w-xl leading-8 text-muted-foreground">هر جهان، یک تاریخچهٔ مستقل دارد. انتخاب‌ها، نقش و مسیر گفت‌وگو در این آرشیو باقی می‌مانند.</p></div><Button onClick={() => setLocation("/characters/new")} className="h-11 rounded-full px-5"><Plus className="ml-2 size-4" />جهان تازه</Button></header>
    <section className="mt-8 grid gap-px overflow-hidden rounded-2xl border archive-rule bg-border sm:grid-cols-3"><div className="bg-card p-5"><p className="text-xs text-muted-foreground">مسیرهای فعال</p><p className="mt-3 text-4xl font-semibold">{isLoading ? "—" : activeRuns.length}</p><p className="mt-2 text-xs text-[color:var(--moss)]">هرکدام یک پایان ممکن دارند</p></div><div className="bg-card p-5"><p className="text-xs text-muted-foreground">حافظهٔ متصل</p><div className="mt-3 flex items-center gap-2 text-lg font-semibold"><Send className="size-4 text-primary" />وب و تلگرام</div><p className="mt-2 text-xs text-muted-foreground">گفتگو از هر کانال به همان داستان می‌رسد.</p></div><div className="bg-card p-5"><p className="text-xs text-muted-foreground">شروع از آرشیو عمومی</p><Button variant="outline" onClick={() => setLocation("/discover")} className="mt-3 rounded-full border-border bg-transparent"><Compass className="ml-2 size-4" />کشف جهان‌ها</Button></div></section>
    <section className="mt-12 grid gap-8 lg:grid-cols-[1.55fr_.8fr]"><div><div className="mb-5 flex items-center justify-between"><div><p className="archive-kicker">در حال خواندن</p><h2 className="mt-1 text-2xl font-semibold">ادامهٔ روایت</h2></div><Button variant="ghost" onClick={() => setLocation("/characters")}>همهٔ شخصیت‌ها<ArrowUpLeft className="mr-2 size-4" /></Button></div>{isLoading ? <div className="story-panel p-8 text-muted-foreground">آرشیو در حال باز شدن است…</div> : featuredRun ? <button onClick={() => setLocation(`/chat/${featuredRun.run.id}`)} className="story-panel group w-full p-7 text-right hover:-translate-y-0.5"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-full bg-secondary text-xl text-secondary-foreground">{featuredRun.storyBot.avatarSymbol}</span><Badge variant="outline" className="border-[color:var(--moss)] text-[color:var(--moss)]">فعال</Badge></div><p className="archive-kicker mt-8">{featuredRun.storyBot.name} · نقش تو: {featuredRun.run.selectedRole}</p><h3 className="mt-2 text-2xl font-semibold">{featuredRun.run.title}</h3><p className="mt-4 max-w-xl leading-8 text-muted-foreground">{featuredRun.run.stateSummary}</p><div className="mt-7 flex items-center gap-2 text-sm font-medium text-primary">ادامه دادن <ArrowUpLeft className="size-4" /></div></button> : <div className="story-panel py-16 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-secondary text-secondary-foreground"><BookOpen className="size-5" /></span><h3 className="mt-5 text-2xl font-semibold">اولین برگ را باز کن</h3><p className="mx-auto mt-3 max-w-md leading-8 text-muted-foreground">یک جهان تازه بساز یا از آرشیو عمومی شروع کن، نقشت را انتخاب کن و مسیر داستان را بساز.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={() => setLocation("/characters/new")} className="rounded-full">ساخت جهان</Button><Button variant="outline" onClick={() => setLocation("/discover")} className="rounded-full border-border bg-transparent">کشف جهان‌ها</Button></div></div>}</div>
      <aside className="border-t archive-rule pt-7 lg:border-r lg:border-t-0 lg:pr-8"><p className="archive-kicker">یادداشت آرشیو</p><h2 className="mt-2 text-2xl font-semibold">چطور پیش می‌رود؟</h2><div className="mt-6 space-y-5"><div><span className="archive-number">01 / ساخت</span><p className="mt-2 text-sm font-medium">شخصیت‌ها</p><p className="mt-1 text-sm leading-7 text-muted-foreground">دستور رفتاری، جهان و شرایط پایان را برای هر شخصیت تعریف کن.</p></div><div className="border-t archive-rule pt-5"><span className="archive-number">02 / نگهداری</span><p className="mt-2 text-sm font-medium">پایان‌های ماندگار</p><p className="mt-1 text-sm leading-7 text-muted-foreground">داستان‌های پایان‌یافته در آرشیو می‌مانند و هر زمان می‌توانی مسیر دیگری را از نو آغاز کنی.</p></div><div className="border-t archive-rule pt-5"><span className="archive-number">03 / ادامه</span><p className="mt-2 text-sm font-medium">ادامه در تلگرام</p><p className="mt-1 text-sm leading-7 text-muted-foreground">پس از اتصال، داستان فعال را به تلگرام ببر تا همان حافظه ادامه پیدا کند.</p></div></div></aside></section>
  </div></div>;
}
