import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Check, Copy, KeyRound, Link2, LockKeyhole, SendToBack, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function SettingsPage() {
  const utils = trpc.useUtils(); const status = trpc.integrations.status.useQuery();
  const [grokApiKey, setGrokApiKey] = useState(""); const [telegramBotToken, setTelegramBotToken] = useState(""); const [grokModel, setGrokModel] = useState(""); const [linkCode, setLinkCode] = useState("");
  const update = trpc.integrations.update.useMutation({ onSuccess: () => { setGrokApiKey(""); setTelegramBotToken(""); utils.integrations.status.invalidate(); toast.success("تنظیمات امن ذخیره شد."); } });
  const generateLink = trpc.integrations.createTelegramLinkCode.useMutation({ onSuccess: result => { setLinkCode(result.code); utils.integrations.status.invalidate(); } });
  const activateWebhook = trpc.integrations.activateTelegramWebhook.useMutation({ onSuccess: () => toast.success("وب‌هوک تلگرام فعال شد.") });
  const submit = (event: FormEvent) => { event.preventDefault(); const payload = { ...(grokApiKey ? { grokApiKey } : {}), ...(telegramBotToken ? { telegramBotToken } : {}), ...(grokModel ? { grokModel } : {}) }; if (!Object.keys(payload).length) return toast.error("حداقل یک مقدار وارد کنید."); update.mutate(payload); };
  const copy = async () => { await navigator.clipboard.writeText(`/start ${linkCode}`); toast.success("فرمان اتصال کپی شد."); };
  return <div className="archive-page"><div className="container max-w-4xl py-10 sm:py-14"><header className="border-b archive-rule pb-9"><p className="archive-kicker">CONNECTION RECORDS / تنظیمات امن</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">کلیدها و مسیرهای اتصال</h1><p className="mt-3 max-w-2xl leading-8 text-muted-foreground">کلید Grok و توکن تلگرام فقط روی سرور، به‌شکل رمزنگاری‌شده نگهداری می‌شوند. این صفحه صرفاً وضعیت پرونده‌ها را نشان می‌دهد، نه رازهای آن‌ها را.</p></header>
    <form onSubmit={submit} className="mt-10 grid gap-5 lg:grid-cols-2"><section className="story-panel p-6"><span className="archive-number">01 / مدل</span><div className="mt-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-secondary text-secondary-foreground"><KeyRound className="size-4" /></span><div><h2 className="font-semibold">Grok</h2><p className="mt-1 text-xs text-muted-foreground">{status.data?.hasGrokApiKey ? "پروندهٔ کلید تکمیل است" : "هنوز کلیدی ثبت نشده"}</p></div></div><div className="mt-6"><Label>کلید API جدید Grok</Label><Input type="password" value={grokApiKey} onChange={event => setGrokApiKey(event.target.value)} className="mt-2 rounded-xl" placeholder="xai-…" autoComplete="off" /></div><div className="mt-4"><Label>مدل</Label><Input value={grokModel} onChange={event => setGrokModel(event.target.value)} className="mt-2 rounded-xl" placeholder={status.data?.grokModel ?? "grok-4.6"} /></div></section>
      <section className="story-panel p-6"><span className="archive-number">02 / ربات</span><div className="mt-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-secondary text-secondary-foreground"><SendToBack className="size-4" /></span><div><h2 className="font-semibold">ربات تلگرام</h2><p className="mt-1 text-xs text-muted-foreground">{status.data?.hasTelegramBotToken ? "پروندهٔ توکن تکمیل است" : "هنوز توکنی ثبت نشده"}</p></div></div><div className="mt-6"><Label>توکن Bot API</Label><Input type="password" value={telegramBotToken} onChange={event => setTelegramBotToken(event.target.value)} className="mt-2 rounded-xl" placeholder="123456:ABC…" autoComplete="off" /></div><p className="mt-4 text-xs leading-6 text-muted-foreground">بعد از انتشار سایت، وب‌هوک را فعال کنید تا یادداشت‌های تلگرام به همان حافظهٔ داستان برسند.</p>{status.data?.hasTelegramBotToken && <Button type="button" variant="outline" disabled={activateWebhook.isPending} onClick={() => activateWebhook.mutate()} className="mt-4 rounded-full border-border bg-transparent">{activateWebhook.isPending ? "در حال فعال‌سازی…" : "فعال‌سازی وب‌هوک"}<SendToBack className="mr-2 size-4" /></Button>}</section>
      <div className="lg:col-span-2"><Button type="submit" disabled={update.isPending} className="rounded-full">{update.isPending ? "در حال ثبت…" : "ثبت امن تغییرات"}<LockKeyhole className="mr-2 size-4" /></Button></div>
    </form>
    <section className="mt-10 border-y archive-rule py-8"><span className="archive-number">03 / پیوند هویت</span><div className="mt-4 grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-secondary text-secondary-foreground"><Link2 className="size-4" /></span><div><h2 className="font-semibold">پیوند حساب تلگرام</h2><p className="mt-1 text-sm text-muted-foreground">{status.data?.isTelegramLinked ? "حساب تلگرام به این آرشیو متصل است." : "برای ادامهٔ یک داستان در تلگرام، یک کد کوتاه بسازید."}</p></div></div>{linkCode && <div className="mt-5 rounded-xl border archive-rule bg-card p-4"><p className="text-sm">این فرمان را در گفتگوی ربات بفرستید. کد تا ده دقیقه معتبر است.</p><div className="mt-3 flex items-center justify-between rounded-lg bg-muted px-3 py-2 font-mono text-sm" dir="ltr"><button onClick={copy} type="button" className="text-primary"><Copy className="size-4" /></button><span>/start {linkCode}</span></div></div>}{status.data?.isTelegramLinked && <p className="mt-4 flex items-center gap-2 text-sm text-[color:var(--moss)]"><Check className="size-4" />اکنون می‌توانید اجرای فعال را از صفحهٔ هر داستان برای تلگرام انتخاب کنید.</p>}</div>{!linkCode && !status.data?.isTelegramLinked && <Button type="button" disabled={!status.data?.hasTelegramBotToken || generateLink.isPending} onClick={() => generateLink.mutate()} className="rounded-full">{generateLink.isPending ? "در حال ساخت…" : "ساخت کد پیوند"}<Sparkles className="mr-2 size-4" /></Button>}</div></section>
  </div></div>;
}
