import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Check, Copy, KeyRound, Link2, LockKeyhole, SendToBack, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function SettingsPage() {
  const utils = trpc.useUtils();
  const status = trpc.integrations.status.useQuery();
  const [grokApiKey, setGrokApiKey] = useState(""); const [telegramBotToken, setTelegramBotToken] = useState(""); const [grokModel, setGrokModel] = useState(""); const [linkCode, setLinkCode] = useState("");
  const update = trpc.integrations.update.useMutation({ onSuccess: () => { setGrokApiKey(""); setTelegramBotToken(""); utils.integrations.status.invalidate(); toast.success("تنظیمات امن ذخیره شد."); } });
  const generateLink = trpc.integrations.createTelegramLinkCode.useMutation({ onSuccess: result => { setLinkCode(result.code); utils.integrations.status.invalidate(); } });
  const activateWebhook = trpc.integrations.activateTelegramWebhook.useMutation({ onSuccess: () => toast.success("وب‌هوک تلگرام فعال شد.") });
  const submit = (event: FormEvent) => { event.preventDefault(); const payload = { ...(grokApiKey ? { grokApiKey } : {}), ...(telegramBotToken ? { telegramBotToken } : {}), ...(grokModel ? { grokModel } : {}) }; if (!Object.keys(payload).length) return toast.error("حداقل یک مقدار وارد کنید."); update.mutate(payload); };
  const copy = async () => { await navigator.clipboard.writeText(`/start ${linkCode}`); toast.success("فرمان اتصال کپی شد."); };
  return <div className="story-grain min-h-screen p-5 sm:p-10"><div className="mx-auto max-w-3xl"><header className="border-b border-white/10 pb-8"><p className="text-xs tracking-[.25em] text-primary">CONNECTIONS / تنظیمات</p><h1 className="mt-3 text-3xl font-semibold">کلیدها و اتصال‌ها</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">کلید Grok و توکن تلگرام فقط روی سرور، به‌شکل رمزنگاری‌شده ذخیره می‌شوند و پس از ثبت دوباره در این صفحه نمایش داده نخواهند شد.</p></header>
    <form onSubmit={submit} className="mt-8 space-y-5"><section className="story-panel p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/12 text-primary"><KeyRound className="size-5" /></span><div><h2 className="font-semibold">Grok</h2><p className="mt-1 text-xs text-muted-foreground">وضعیت: {status.data?.hasGrokApiKey ? "کلید ثبت شده" : "کلیدی ثبت نشده"}</p></div></div><div className="mt-5"><Label>کلید API جدید Grok</Label><Input type="password" value={grokApiKey} onChange={event => setGrokApiKey(event.target.value)} className="mt-2" placeholder="xai-…" autoComplete="off" /></div><div className="mt-4"><Label>مدل</Label><Input value={grokModel} onChange={event => setGrokModel(event.target.value)} className="mt-2" placeholder={status.data?.grokModel ?? "grok-4.6"} /></div></section>
      <section className="story-panel p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-sky-400/10 text-sky-300"><SendToBack className="size-5" /></span><div><h2 className="font-semibold">ربات تلگرام</h2><p className="mt-1 text-xs text-muted-foreground">وضعیت: {status.data?.hasTelegramBotToken ? "توکن ثبت شده" : "توکنی ثبت نشده"}</p></div></div><div className="mt-5"><Label>توکن Bot API</Label><Input type="password" value={telegramBotToken} onChange={event => setTelegramBotToken(event.target.value)} className="mt-2" placeholder="123456:ABC…" autoComplete="off" /></div><p className="mt-3 text-xs leading-6 text-muted-foreground">پس از انتشار سایت، اتصال وب‌هوک ربات را فعال کنید. پیام‌های تلگرام به همان داستان و حافظهٔ وب می‌رسند.</p>{status.data?.hasTelegramBotToken && <Button type="button" variant="outline" disabled={activateWebhook.isPending} onClick={() => activateWebhook.mutate()} className="mt-4 rounded-xl border-white/10">{activateWebhook.isPending ? "در حال فعال‌سازی…" : "فعال‌سازی وب‌هوک تلگرام"}<SendToBack className="mr-2 size-4" /></Button>}</section>
      <Button type="submit" disabled={update.isPending} className="rounded-xl">{update.isPending ? "در حال ذخیره…" : "ذخیرهٔ امن تنظیمات"}<LockKeyhole className="mr-2 size-4" /></Button>
    </form>
    <section className="story-panel mt-8 p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/12 text-primary"><Link2 className="size-5" /></span><div><h2 className="font-semibold">پیوند حساب تلگرام</h2><p className="mt-1 text-xs text-muted-foreground">وضعیت: {status.data?.isTelegramLinked ? "حساب تلگرام متصل است" : "هنوز پیوندی ایجاد نشده"}</p></div></div>{linkCode ? <div className="mt-5 rounded-xl border border-primary/25 bg-primary/10 p-4"><p className="text-sm">این فرمان را در گفتگوی ربات خود بفرستید. کد تا ده دقیقه معتبر است.</p><div className="mt-3 flex items-center justify-between rounded-lg bg-background/70 px-3 py-2 font-mono text-sm" dir="ltr"><button onClick={copy} type="button" className="text-primary"><Copy className="size-4" /></button><span>/start {linkCode}</span></div></div> : <Button type="button" disabled={!status.data?.hasTelegramBotToken || generateLink.isPending} onClick={() => generateLink.mutate()} className="mt-5 rounded-xl">{generateLink.isPending ? "در حال ساخت کد…" : "ساخت کد یک‌بارمصرف"}<Sparkles className="mr-2 size-4" /></Button>}{status.data?.isTelegramLinked && <p className="mt-4 flex items-center gap-2 text-sm text-primary"><Check className="size-4" />اکنون می‌توانید اجرای فعال را از صفحهٔ هر داستان برای تلگرام انتخاب کنید.</p>}</section>
  </div></div>;
}
